<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Desktop</name>
   <tag></tag>
   <elementGuidId>1bf259f9-b0b2-4306-b252-a7c3570a01d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.rct-node.rct-node-parent.rct-node-collapsed > span.rct-text > label > span.rct-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tree-node']/ol/li/ol/li/span/label/span[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Desktop&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e70ebe3f-f427-4b13-89b5-f0a3d06348fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rct-title</value>
      <webElementGuid>40ac48ea-719b-4ccc-8988-6bf6cc8d7b26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Desktop</value>
      <webElementGuid>6a7b6c51-a814-4121-9bdd-3d3b2837c9fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tree-node&quot;)/ol[1]/li[@class=&quot;rct-node rct-node-parent rct-node-expanded&quot;]/ol[1]/li[@class=&quot;rct-node rct-node-parent rct-node-collapsed&quot;]/span[@class=&quot;rct-text&quot;]/label[1]/span[@class=&quot;rct-title&quot;]</value>
      <webElementGuid>973118bc-bbd2-4a40-85c6-cb10d9128e6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tree-node']/ol/li/ol/li/span/label/span[3]</value>
      <webElementGuid>29a4ee2b-8416-4e3a-8023-71cf532fce9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::span[4]</value>
      <webElementGuid>180328df-4e78-442c-9b23-bccf5064a572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check Box'])[2]/following::span[8]</value>
      <webElementGuid>2ffab4a5-4481-4d97-8f7a-bc6f91cc3153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Documents'])[1]/preceding::span[3]</value>
      <webElementGuid>d4a91850-87b1-4d1e-87be-3e8bb01ebc65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Downloads'])[1]/preceding::span[7]</value>
      <webElementGuid>77741e0d-6535-4106-8ae2-d74579c98582</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Desktop']/parent::*</value>
      <webElementGuid>213006a5-4505-4a58-9763-f7725ad61505</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ol/li/span/label/span[3]</value>
      <webElementGuid>8f1494fb-b187-4b2a-9526-98dc7abbd04b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Desktop' or . = 'Desktop')]</value>
      <webElementGuid>1b0669c2-e61f-4868-b598-1991e1656d7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
